### ISSUE TITLE
Download completion sound?

### ISSUE THREAD

**Issue by mr-tango** [igorlogius/notify-on-download-complete#1]
This isn't mentioned in the extension's description, so it appears to not be the case.

If there is no sound, could you add toggle-button options for successful, and unsuccessful, download completions?

Thanks!

**Comment by igorlogius** [comment]
Sure, i'll take a look if i can add a few static sounds options.  (bell, glass(pitch) or something) 

And maybe for later i'll try to add the function that a user to can set a custom sound.

**Comment by mr-tango** [comment]
That would be great. This was native to Firefox, but they removed it, and I think a lot of people would like it back. I've found only two two extensions that restore it, that were last updated...
* four yrs. ago: https://addons.mozilla.org/en-US/firefox/addon/download-sound
* four mo. ago: https://addons.mozilla.org/en-US/firefox/addon/gnome-download-notifications

So you don't have much competition for download sounds, and many will avoid the first because it's so old. If you add them, then definitely put "sounds" into your extension name so people can find it more easily, and consider highlighting that info near the top of your extension's description. Also, those other two don't have many sounds included, and most people don't have the right audio files sitting around to upload, so I think you could surpass them easily if you could just include a larger selection of good sounds than them.

**Comment by igorlogius** [comment]
> If you add them, then definitely put "sounds" into your extension name so people can find it more easily, and consider highlighting that info near the top of your extension's description. 

I'll definitely add the sound info into the  addon summary  and description , ... but i am not sure if i really want to rename it yet. 
I mean a sound is also a kind of notification ... so at least the addon name isn't wrong. But i'll  think about it. 

> if you could just include a larger selection of good sounds than them.

Actually, i would rather leave it up to the users to choose a sound they will like. 
This will also have the benefit of keeping the addon small, and saves me the hassel of having to maintain a "good" sound library, which is kind of a personal preference ...  but  maybe i could include a few sound ... i think about that too. 

---
Implementation Notes:  (aka. things to add/create/change) 

1. option page 
2. option to completely enabled or disable the sounds 
3. default sounds for  success and failure of a download.   
4. two input/upload element for the user to store a custom sound for success and failure
5. storage permission to save the custom files  (should be enough without the unlimited storage)
6. volume sliders/input fields to configure the volume for the selected audio 
7. labels/info about the upload/store file restrictioons (types: wav,ogg,mp3,..  &  max-size)

**Comment by igorlogius** [comment]
Version 1.1.1  adds an `Preferences` page where users can set custom sounds for the download  `Completed` and  `Interrupted`  events.
Per default  there is `no sound` registered  but users who want them, can now easily add them.  Two example sounds files can be found in the repository. 

@mr-tango  Hope that works for you. 

Preview Addon  `Preferences`  Page
![capture-2022-04-11_20:18:25](https://user-images.githubusercontent.com/67047467/162804023-74b6bb09-dc12-4d0d-8d5c-bf537fca4cd3.jpg)
